version: "3.7"

services:

  cashgps:
    build: ./
    ports:
      - 4000:4000
    working_dir: /app
    volumes:
      - ./src:/app/src
    container_name: cashgps
    depends_on:
      - mysql

  mysql:
    image: mysql:5.7
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_HOST: mysql
    volumes:
      - mysql-volume:/var/lib/mysql
    container_name: mysql
    ports:
      - 3306:3306

  flyway:
    image: boxfuse/flyway:5.2.4
    command: -url=jdbc:mysql://mysql -schemas=cashgps -user=root -password=root -connectRetries=60 migrate
    volumes:
      - .:/flyway/sql
    depends_on:
      - mysql
volumes:
  mysql-volume:
